/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PangoToolbar {
        "headerSubTitle": string;
        "headerTitle": string;
        "pangoHome": string;
        "showLoadingBar": boolean;
    }
}
declare global {
    interface HTMLPangoToolbarElement extends Components.PangoToolbar, HTMLStencilElement {
    }
    var HTMLPangoToolbarElement: {
        prototype: HTMLPangoToolbarElement;
        new (): HTMLPangoToolbarElement;
    };
    interface HTMLElementTagNameMap {
        "pango-toolbar": HTMLPangoToolbarElement;
    }
}
declare namespace LocalJSX {
    interface PangoToolbar {
        "headerSubTitle"?: string;
        "headerTitle"?: string;
        "pangoHome"?: string;
        "showLoadingBar"?: boolean;
    }
    interface IntrinsicElements {
        "pango-toolbar": PangoToolbar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pango-toolbar": LocalJSX.PangoToolbar & JSXBase.HTMLAttributes<HTMLPangoToolbarElement>;
        }
    }
}
