name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build components
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Verify component outputs
        run: |
          echo "=== Dist Output ==="
          ls -la dist/
          echo "=== Loader Output ==="
          ls -la loader/
          echo "=== Custom Elements Output ==="
          ls -la dist/components/ || echo "No custom elements output found"

      - name: Check for uncommitted changes
        run: |
          git diff --exit-code || {
            echo -e "\033[1;31m⚠️ Build outputs are not committed ⚠️\033[0m"
            echo -e "\033[1;31mPlease run 'npm run build' and commit the changes.\033[0m"
            exit 1
          }